site_name: drfdemo
site_description: Example code for my DRF talk at DjangoCon US 2018
repo_url: https://github.com/drewbrew/djangoconus2018-drf-talk
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/drewbrew">drewbrew</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
